# Python program to scrape ‘software developer’ job listings from ‘Monster.com’. It should include all the jobs listed for the next 5 pages.

In [1]:
#Importing required libraries
import selenium
import pandas as pd
from selenium import webdriver
import time

In [2]:
#Connect to web driver
driver=webdriver.Chrome(r"D://chromedriver.exe")  #r converts string to raw string
#If not r, we can use executable_path = "C:/path name"

In [3]:
#Getting the website to driver
driver.get('https://www.monsterindia.com/srp/results?query=software%20developer&searchId=f75672d0-0f03-4a74-8607-45bda5e792df')
#When we run this line, automatically the webpage will be opened

In [4]:
#Taking the empty lists
job_title=[]
company=[]
location=[]
experience=[]

#As we need to scrap for 5 pages, we are running a for loop
for i in range(0,5):
    for j in driver.find_elements_by_xpath("//h3[@class='medium']/a"):
        job_title.append(j.text)
    for k in driver.find_elements_by_xpath("//span[@class='company-name']/a"):
        company.append(k.text)
    for l in driver.find_elements_by_xpath("//div[@class='col-xxs-12 col-sm-5 text-ellipsis']/span/small"):
        location.append(l.text)
    for e in driver.find_elements_by_xpath("//div[@class='exp col-xxs-12 col-sm-3 text-ellipsis']/span/small"):
        experience.append(e.text)
    driver.find_element_by_xpath("//button[@class='btn-next-prev btn-next']").click()
    time.sleep(3)

In [5]:
job_title

['Fresher - Software developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer Job For Freshers',
 'Software Engineer For Freshers',
 'Salesforce Developer',
 'System Engineer For Freshers',
 'Software developer/Software Testing',
 'Software Developer',
 'Software Developer Job For Freshers',
 'IP/MPLS Protocol Software Development',
 'Full Stack Developer',
 'Java Full Stack Developer - Primary Skills Java, Angular or React.Js',
 'UI Developer/Sr. UI Developer : Location -Noida : Experience : 4-12yrs : Full time and Permanent Job',
 'Java/.Net Developers',
 '***we have an urgent requirement on SQL, SSIS, Power BI trained freshers with one of the MNC . ***',
 'Software Developer',
 'Software Developer',
 'Fresher - software developer',
 'Software Developer',
 'Software Developer',
 'Fresher - software developer',
 'UI Developer/Sr. UI Developer : Location -Noida : Experience : 4-12yrs : Full time and Permanent Job',
 'Java/.Net Developers',
 '***we have an urgent requirement on SQL, SSIS, Power BI trained freshers with one of the MNC . ***',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Fresher - software developer',
 'Fresher - software developer',
 'ETL Developer / Datastage Developer',
 'Dot Net Developer',
 'Sr. Java Developers- Females on career Break-Returnee program',
 'Software Developer',
 'Senior Software Developer',
 'Sr Software Developer',
 'Fresher - software developer',
 'Fresher - software developer',
 'Software Developer',
 'Android Developer',
 '"Immediate Openings for software Developers"',
 'BigData Engineer',
 '****we have an urgent requirement on Testing trained freshers with one of the MNC . ****',
 'Software Developer',
 'Software Developer - Freshers - (.NET / JAVA / Angular/PHP/Python)',
 'PHP Zend Developer Mumbai Location',
 'Java Stack Developer- RETURN TO WORK- FEMALES ONLY',
 'Data Scientist',
 'Software Developer',
 'Senior Software Developer',
 'Software Developer',
 'Software Engineer For Freshers',
 'Software Engineer For Freshers',
 'API Backend and UI Frontend FullStack',
 'Software Engineer For Freshers',
 'E Commerce Software Developer',
 'Software Developer (Java)',
 'Software Developer Job For Freshers',
 'Software Engineer For Freshers',
 'Urgent Opening for Dot net Developer for Pan India',
 'Software Developer Required in CANADA & AUSTRALIA',
 'Senior Software Developer',
 'Software Developer Job For Freshers',
 '.Net Software Developer | 1-2 Years | 20-25 K',
 'Software Engineer For Freshers',
 'Java Developer Job For Freshers',
 'Software Developer (PHP)',
 'Software Developer/Software Engineer/Software Programmer/Fresher in Dot Net - Mumbai based',
 'Software Developer',
 'Java Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Software Developer',
 'Android Developer/ Software Developer / Software Engineer / Software Programmer/Fresher',
 'Software Developer',
 'Software Programmer / Software Developer',
 'Software Engineer',
 'Software Programmers - AI Developers',
 'Sr. React JS Developer',
 'Sr. UI Developer - 12 Yrs Exp',
 'Hybrid Mobile App Developer',
 'Java Developer',
 'Android Firmware Developer',
 'Angular JS Developer',
 'Clinical System Developer',
 'Mindship Software Engineer in Test (Automation & Manual)',
 'Web Application Development',
 'Opening for Salesforce (SFDC) Developer in PAN India',
 'Bigdata Engineer',
 '.Net Core Developer_ Intersoft Data Labs',
 'Oracle Plsql Developer_ Intersoft Data Labs',
 'DevOps Engineer- Python & AWS',
 'Software Engineer',
 'Software Engineer - Full Stack Developer',
 'Senior Software Engineer- .Net',
 'Web Application Development',
 'Opening for Salesforce (SFDC) Developer in PAN India',
 'Bigdata Engineer',
 '.Net Core Developer_ Intersoft Data Labs',
 'Oracle Plsql Developer_ Intersoft Data Labs',
 'DevOps Engineer- Python & AWS',
 'Software Engineer - Full Stack Developer',
 'Software Trainee',
 'Software Engineer - WPF',
 'Backend Developer',
 'Full Stack Developer',
 'Full Stack Developer',
 'Sr. Developer (Java full strack), associate',
 'Sr.Developer Java Stalk',
 'Full Stack Web Developer',
 'Opening for Angular Developer (WFH) Anywhere in India',
 'Executive -Business development',
 'Automation / Monitoring Engineer',
 'Opening for MEAN Stack Developer(WFH) Anywhere in India',
 'Senior Clinical SAS Programmer-SDTM/CDISC Expert',
 'Full Stack Engineer',
 'dot net web developers',
 'Senior React-JS Developer/Front-End Developer - Permanent WFH/Remote Work Opportunity',
 'Software Developer For Freshers',
 'Software Engineer For Freshers']

In [6]:
location

['Chennai, Hyderabad / Secunderabad',
 'Bengaluru / Bangalore, Chennai',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Kolkata',
 'Bengaluru / Bangalore, Chennai',
 'Vijayawada, Visakhapatnam',
 'Mumbai',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Bengaluru / Bangalore',
 'Mumbai, Pune',
 'Ranchi',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Thiruvananthapuram / Trivandrum',
 'Noida',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Chennai',
 'Pune',
 'Bengaluru / Bangalore, Chennai',
 'Hyderabad / Secunderabad',
 'Hubli',
 'Bengaluru / Bangalore, Chennai',
 'Noida',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Chennai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Hubli',
 'Bengaluru / Bangalore, Chennai',
 'Bengaluru / Bangalore, Chennai',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Mohali',
 'Gurgaon / Gurugram',
 'Pune',
 'Bengaluru / Bangalore',
 'Noida',
 'Bengaluru / Bangalore, Chennai',
 'Bengaluru / Bangalore, Chennai',
 'Amritsar',
 'Delhi',
 'Chennai, Coimbatore',
 'Remote',
 'Hyderabad / Secunderabad',
 'Ahmedabad',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Mumbai, Mumbai City, Navi Mumbai, Thane',
 'Gurgaon / Gurugram',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Delhi, Gurgaon / Gurugram',
 'Kozhikode / Calicut, Cochin / Kochi / Ernakulam',
 'Kolkata',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore, Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore, Chennai',
 'Australia, Canada',
 'Visakhapatnam',
 'Mumbai',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Pune',
 'Mumbai',
 'Bengaluru / Bangalore',
 'Jaipur',
 'Pune',
 'Coimbatore',
 'Canada, Hong Kong',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Navi Mumbai',
 'Chennai',
 'Delhi, Gurgaon / Gurugram',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore, Pune',
 'Pune',
 'Mohali',
 'Pune',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Chennai, Gurgaon / Gurugram',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore, Delhi',
 'Bengaluru / Bangalore, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Bengaluru / Bangalore',
 'Canada, Germany',
 'Mohali',
 'Kolkata',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore, Delhi',
 'Bengaluru / Bangalore, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Bengaluru / Bangalore',
 'Mohali',
 'Visakhapatnam',
 'Mohali',
 'Bengaluru / Bangalore',
 'Mysore',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Gurgaon / Gurugram',
 'Gurgaon / Gurugram',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Nashik',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore, Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Delhi',
 'Bengaluru / Bangalore']

In [7]:
company

['Intellect Design Arena Limited',
 'I soft',
 'Silaris Informations Private Limited',
 'Strateology IT Solutions Private Limited',
 'Expertia Ai Technologies Private Limited',
 'Pepplo Consulting',
 'Larsen & Toubro Infotech Limited',
 'Bloom Berry Solution',
 'Biz Industries',
 'Biz Industries',
 'Vera Solution Private Limited',
 'Biz Industries',
 'Infomedia Solutions And Consultant',
 'Sarfarosh Bharat Company',
 'Biz Industries',
 'Enroll N Pro',
 'Team Hunt Hr Solutions',
 'PlaceElements HR',
 'Talent Solutions',
 'Axis Minds Consultancy Services Llp',
 'Axness Technologies Private Limited',
 'Freelancer Prabhakar Naidu',
 'Sharp Facility',
 'I soft',
 'Vamtrick Business Solutions Private Limited',
 'I soft',
 'Talent Solutions',
 'Axis Minds Consultancy Services Llp',
 'Axness Technologies Private Limited',
 'Freelancer Prabhakar Naidu',
 'Sharp Facility',
 'Vamtrick Business Solutions Private Limited',
 'I soft',
 'I soft',
 'Intelliaura Technology Solutions Private Limited',
 'Heka HR',
 'Sampark',
 'FreeLancer Urvi',
 'Search Agency Performance Marketing India Private Limited',
 'Search Bridge Consulting',
 'I soft',
 'I soft',
 'Minda Solution Tech Mark',
 'WiseArmour Technology India Private Limited',
 'Diraa HR Services',
 'Isg Compusolutions India Private Limited',
 'Axness Technologies Private Limited',
 '3i Infotech Limited',
 'Sampark',
 'Novateur IT Technologies India Private Limited',
 'Skan Tech Consultancy',
 'Adot Consultancy',
 'Biz Industries',
 'Biz Industries',
 'Quess IT Staffing (Formerly known as Magna Infotech)',
 'Biz Industries',
 'Singapore Infotech India Private Limited',
 'Xecom Information Technologies Private Limited',
 'Biz Industries',
 'Biz Industries',
 'Nelito Systems Limited',
 'Pear Visa Immigration Services Private Limited',
 'White Willow Software Pvt Ltd',
 'Biz Industries',
 'Disha Recruitment Services',
 'Biz Industries',
 'Biz Industries',
 'Xecom Information Technologies Private Limited',
 'Prime Software Solution',
 'Tech Mahindra Limited',
 'Riju Karan (Proprietor Of Toyota Climax India)',
 'Coral Bling Services Private Limited',
 'Diraa HR Services',
 'Pleco Migration Private Limited',
 'Tech Mahindra Limited',
 'Effiasoft Private Limited',
 'Singh RanjayKumar(Proprietor Of Zee India Co)',
 'V.S.T.Motors Private Limited',
 'Skan Tech Consultancy',
 'TruVoice.ai',
 'Devenir Software Private Limited',
 'ExterNetworks Inc',
 'Singapore Infotech India Private Limited',
 'Infomedia Solutions And Consultant',
 'Meritech Software Pvt Ltd',
 'SQR Infotech Private Limited',
 'Heylus Hr Private Limited',
 'Impact HR Services Private Limited',
 'VServ Business Solutions Private Limited',
 'VServ Business Solutions Private Limited',
 'Applicantz Inc',
 'Infinix Immigration Service Private Limited',
 'Meritech Software Pvt Ltd',
 'Kovair Software Pvt. Ltd.',
 'Heylus Hr Private Limited',
 'Impact HR Services Private Limited',
 'VServ Business Solutions Private Limited',
 'VServ Business Solutions Private Limited',
 'Applicantz Inc',
 'Meritech Software Pvt Ltd',
 'Miracle Software Systems India Private Limited',
 'Meritech Software Pvt Ltd',
 'eAnswer Network India Private Limited',
 'Infopine Consultancy Services Private Limited',
 'eAnswer Network India Private Limited',
 'Sampark',
 'Sampark',
 'Strategic Technology Resources International Private Limited',
 'Serviam Consultancy Services',
 'Applicantz Inc',
 'Strategic Technology Resources International Private Limited',
 'Clinasia Labs Private Limited',
 'Indee Software Private Limited',
 'Enroll N Pro',
 'ValueLabs LLP',
 'Biz Industries',
 'Biz Industries']

In [8]:
experience

['5-8 Years',
 '0-1 Years',
 '1-8 Years',
 '4-8 Years',
 '0-1 Years',
 '3-5 Years',
 '4-9 Years',
 'Fresher',
 '0-2 Years',
 '0-2 Years',
 '4-10 Years',
 '0-2 Years',
 '2-5 Years',
 '0-2 Years',
 '0-2 Years',
 '5-10 Years',
 '2-5 Years',
 '3-12 Years',
 '4-12 Years',
 '0-2 Years',
 'Fresher',
 '4-8 Years',
 '0-2 Years',
 '0-1 Years',
 '0-1 Years',
 '1-4 Years',
 '0-1 Years',
 '4-12 Years',
 '0-2 Years',
 'Fresher',
 '4-8 Years',
 '0-2 Years',
 '0-1 Years',
 '1-4 Years',
 '0-1 Years',
 '0-1 Years',
 '3-13 Years',
 '4-7 Years',
 '3-8 Years',
 '3-6 Years',
 '3-8 Years',
 '5-10 Years',
 '0-1 Years',
 '0-1 Years',
 '0-1 Years',
 '2-5 Years',
 '0-5 Years',
 '4-14 Years',
 'Fresher',
 '2-4 Years',
 '0-2 Years',
 '3-9 Years',
 '3-8 Years',
 '3-8 Years',
 '1-3 Years',
 '5-9 Years',
 '1-2 Years',
 '0-2 Years',
 '0-2 Years',
 '5-15 Years',
 '0-2 Years',
 '3-10 Years',
 '1-6 Years',
 '0-2 Years',
 '0-2 Years',
 '3-6 Years',
 '2-7 Years',
 '5-10 Years',
 '0-2 Years',
 '1-2 Years',
 '0-2 Years',
 '0-2 Years',
 '1-6 Years',
 '0-1 Years',
 '4-6 Years',
 '0-3 Years',
 '2-3 Years',
 '0-5 Years',
 '2-7 Years',
 '4-6 Years',
 '1-7 Years',
 '0-5 Years',
 '4-8 Years',
 '2-4 Years',
 '2-5 Years',
 '5-10 Years',
 '8-13 Years',
 '3-7 Years',
 '1-3 Years',
 '2-4 Years',
 '3-6 Years',
 '0-4 Years',
 '0-2 Years',
 '2-3 Years',
 '4-10 Years',
 '3-8 Years',
 '2-10 Years',
 '4-9 Years',
 '5-15 Years',
 '1-5 Years',
 '2-4 Years',
 '5-6 Years',
 '2-3 Years',
 '4-10 Years',
 '3-8 Years',
 '2-10 Years',
 '4-9 Years',
 '5-15 Years',
 '2-4 Years',
 '0-1 Years',
 '2-4 Years',
 '2-6 Years',
 '2-4 Years',
 '1-4 Years',
 '5-9 Years',
 '5-9 Years',
 '2-4 Years',
 '3-5 Years',
 '2-5 Years',
 '5-15 Years',
 '3-6 Years',
 '6-12 Years',
 '2-7 Years',
 '1-4 Years',
 '5-8 Years',
 '0-2 Years',
 '0-2 Years']

In [9]:
print(len(job_title),len(company),len(location),len(experience))

125 117 127 127

In [10]:
jobs=pd.DataFrame({})
jobs['Title']=job_title[:117]
jobs['Company Name']=company
jobs['Location']=location[:117]
jobs['Experience']=experience[:117]
jobs

,Title,Company Name,Location,Experience
0,Fresher - Software developer,Intellect Design Arena Limited,"Chennai, Hyderabad / Secunderabad",5-8 Years
1,Software Developer,I soft,"Bengaluru / Bangalore, Chennai",0-1 Years
2,Software Developer,Silaris Informations Private Limited,Delhi,1-8 Years
3,Software Developer,Strateology IT Solutions Private Limited,Hyderabad / Secunderabad,4-8 Years
4,Software Developer,Expertia Ai Technologies Private Limited,Bengaluru / Bangalore,0-1 Years
...,...,...,...,...
112,"Sr. Developer (Java full strack), associate",Indee Software Private Limited,Mysore,2-4 Years
113,Sr.Developer Java Stalk,Enroll N Pro,"Bengaluru / Bangalore, Hyderabad / Secunderabad",1-4 Years
114,Full Stack Web Developer,ValueLabs LLP,Gurgaon / Gurugram,5-9 Years
115,Opening for Angular Developer (WFH) Anywhere i...,Biz Industries,Gurgaon / Gurugram,5-9 Years
116,Executive -Business development,Biz Industries,Bengaluru / Bangalore,2-4 Years

# python program to scrape ‘data scientist’ job listings for location ‘New Delhi’ from ‘Monster.com’. It should include all the jobs listed for the next 5 pages.

In [11]:
#Connect to web driver
driver=webdriver.Chrome(r"D://chromedriver.exe")  #r converts string to raw string
#If not r, we can use executable_path = "C:/path name"

In [12]:
#Getting the website to driver
driver.get('https://www.monsterindia.com/srp/results?query=Data%20Scientist&locations=Delhi&searchId=7cf23751-9293-4870-aae7-5a667bab550b')

#When we run this line, automatically the webpage will be opened

In [13]:
#Taking the empty lists
job_title=[]
company=[]
location=[]
experience=[]

#As we need to scrap for 5 pages, we are running a for loop
for i in range(0,5):
    for j in driver.find_elements_by_xpath("//h3[@class='medium']/a"):
        job_title.append(j.text)
    for k in driver.find_elements_by_xpath("//span[@class='company-name']/a"):
        company.append(k.text)
    for l in driver.find_elements_by_xpath("//div[@class='col-xxs-12 col-sm-5 text-ellipsis']/span/small"):
        location.append(l.text)
    for e in driver.find_elements_by_xpath("//div[@class='exp col-xxs-12 col-sm-3 text-ellipsis']/span/small"):
        experience.append(e.text)
    driver.find_element_by_xpath("//button[@class='btn-next-prev btn-next']").click()
    time.sleep(3)

In [14]:
job_title

['Data Scientist',
 'Data Analyst / Fresher / Data Scientist / Graduate MNA Fresher - MNC - 9717266846',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 8745833047 | 9999340492',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC -7065337397 | 9717266846',
 'Data Scientist - Machine Learning',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 8745833047 | 7065337397',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst – Fresher – Data Scientist – Graduate - Fresher 7303778896',
 'Data Analyst – Fresher – Data Scientist – Graduate - Fresher 8077828639 | 7303778896',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 8218334341 | 8077828639',
 'Data Analyst – Fresher – Data Scientist – Graduate - Fresher 7303778896 | 9560245147',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst / Fresher / Data Scientist / Graduate Fresher - MNC - 7303778896 | 9560245147',
 'Data Analyst – Fresher – Data Scientist – Graduate - Fresher 7303778896 | 9560245147 | 6397800351',
 'Data Entry Operator/Data Entry Executive',
 'Data Management Specialist, Data Entry, Data Executive',
 'Data Engineer',
 'Data administration Data Entry / home based job',
 'Part Time Jobs, Work From Home Jobs, Online Data Entry Jobs, Data Entry Job, Online Jobs, Data Entry',
 'Online Data Entry Jobs, Work From Home, Part Time Job, Data Entry, Online Typing Job, Data Entry Job',
 'Data Entry',
 'Data Entry',
 'Data Entry Operator',
 'Data Entry Operator',
 'Data Entry Operator',
 'Data Analyst , Senior Data Analyst , Data Analyst - Tech Lead',
 'Data Entry',
 'Data Entry',
 'Data Analyst',
 'DATA ANALYST',
 'Online Data Entry, Work From Home Jobs, Part Time Jobs, Data Entry, Typing Jobs, Data Entry Jobs',
 'Online Data Entry Jobs, Part Time Jobs, Work From Home, Data Entry Jobs, Data Entry, Typing jobs',
 'Online Data Entry Jobs, Work From Home, Data Entry, Part Time Jobs, Typing Jobs, Data Entry Jobs',
 'Data Entry, Part Time Jobs, Work From Home, Online Data Entry Jobs, Simple Data Entry, Typing Jobs',
 'Data Retrieval Specialists - eDiscovery - FTE',
 'Work from Home Data Entry Jobs (Typing, Excel Numeric, Copy-Paste, Handwriting)',
 'Home Based Jobs, Online Data Entry, Part Time Jobs, Data Entry Jobs, Work From Home, Data Entry, WFH',
 'Online Data Entry Jobs, Part Time Jobs, Work From Home Jobs, Data Entry Job, Online Jobs, Data Entry',
 'Data Entry Jobs, Home Based Jobs, Simple Data Entry Jobs, Work at Home Jobs, Online Data Entry Jobs',
 'Automation Engineer_ Intersoft Data Labs',
 'Data Processing/Back-end Executive',
 'Data Quality Management Specialist',
 'work from home, data entry jobs, part time, jobs for students, home based, typing jobs, data entry',
 'Data Entry Jobs, Work From Home Jobs, Part Time Jobs available, Online Data Entry Jobs, Typing Jobs',
 'Data Entry Jobs, Work From Home Jobs, Part Time Jobs available, Online Data Entry Jobs, Typing Jobs',
 'CCIE - Data center',
 'Hiring For Back office operation/Backend /Data Entry/',
 'Hiring For Back office operation/Backend /Data Entry/',
 'Simple Typing Jobs, Online Data Entry Jobs, Work From Home Jobs, Work at Home Jobs, Data Entry Jobs',
 'DATA QUALITY ANALYST',
 'Simple Typing Jobs, Online Data Entry Jobs, Work From Home Jobs, Work at Home Jobs, Data Entry Jobs',
 'Data Entry Jobs, Work From Home Jobs, Part Time Job, Online Data Entry Jobs, Home based Jobs, Typing',
 'Data Entry Operator',
 'Work From Home Jobs, Data Entry Jobs, Part Time Jobs, Online Data Entry, Home Based Jobs, Typing Job',
 "Opening For Data Entry Operator Fresher's",
 'Data engineer',
 '.Net Core Developer_ Intersoft Data Labs',
 'Oracle Plsql Developer_ Intersoft Data Labs',
 'Customer Support/Customercare Executive/Data entry',
 'Lab Technician Job For Freshers',
 'Oracle meter data management consultant',
 'Data Analyst | Business Analytics | Data Science - Fresher Graduate - 7065337388',
 'Data Architect',
 'Data Entry Urgent Hiring',
 'Data Analyst',
 'LIDAR data processing engineers',
 'BACKEND EXECUTIVE | | Data entry operator | | OFFICE EXECUTIVE',
 'Data Entry',
 'Java Full Stack Developer_ Intersoft Data Labs',
 'DATA ENTRY | | BACK OFFICE/RECEPTION/COMPUTER OPERATOR',
 'Online Data Entry / Form Filling / Computer Operator',
 'COMPUTER OPERATOR & DATA ENTRY BACK OFFICE EXECUTIVE',
 'Data Entry @ Rs.300/Page l Work From Home Jobs',
 'Lab Technician Job For Freshers',
 'Part Time Jobs, Work From Home Jobs, Data Entry, Computer Operator Jobs, Data Entry Jobs, Typing Job',
 'Lab Technician Job For Freshers',
 'Laboratory Assistance Job For Freshers',
 'Pathological Job For Freshers',
 'work from home, data entry jobs, part time, jobs for students, home based, typing jobs, data entry',
 'Laboratory Assistance For Freshers',
 'Online Data entry Jobs, Simple Typing jobs, Part Time Jobs, Work From Home jobs, Data Entry Jobs',
 'Urgent Requirement for Telecaliing executives Data entry operator',
 'Machine Learning Data Science trainer',
 'work from home, data entry jobs, part time jobs, work from home jobs, online data entry jobs, typist',
 'Data Entry Operator',
 'Sales Manager-Data Security Solution/Cloud Solution',
 'data entry operators',
 'Data Entry operators',
 'PART TIME WORK@Home DATA Entry/Home Based WORK/Typing JOB',
 'PART TIME WORK@Home DATA Entry/Home Based WORK/Typing JOB',
 'PART TIME WORK@Home DATA Entry/Home Based WORK/Typing JOB',
 'Mega opening for back office data entry for MNC company ...Apply now',
 '24X7 IN YOUR HAND OFFLINE HOME DATA TYPING JOB 44000 MONTHLY SALARY',
 'REGARDING WORK FROM HOME JOB HIRING FOR DATA ENTRY',
 'Laboratory Technician For Freshers',
 'Data Entry Operator ( Fresher )',
 'Lab Chemist Job For Freshers',
 'Account Assistant/Data Entry',
 'Data Entry and Back office Operations',
 'Data Entry Operator FOR PHARMA COMPANY',
 'B.sc Nursing For Freshers',
 'Part Time Typing Work / Home Based Work / Freelancer / Data Entry Job',
 'Part Time Typing Work / Home Based Work / Freelancer / Data Entry Job',
 'Openings for Part Time home based Computer Data Entry Operator Jobs',
 'Part Time Full Time Data Typing Work / Work From Home / Freelancer Job',
 'Computer Operator',
 'DATA ENTRY OPERATOR FOR HITACHI',
 'URGENT REQUIRED DATA ENTRY EXECUTIVE FOR SHAHI EXPORTS',
 'Simple Typing Jobs are available, Online Data Entry Jobs, Work From Home Jobs, Part Time Jobs',
 'Part time/Full time Job Work from Home/Data Entry Typing Job',
 'Data Entry Clerk FOR BOB',
 'Data Entry Operator FOR PHARMA COMPANY',
 'Fresher data entry and back office',
 'Data administration Data Entry / home based job',
 'Data administration Data Entry / home based job',
 'Trainee - Data Science, Artificial Intelligence & Data Analytics',
 '• Get good payment on home based data entry work',
 'Part-time home based data entry operator/typing Jobs',
 'Director Data Science-NGO-Delhi-10yrs+-12lakhs',
 'Earn Rs.45k PM Freelance Part Time Work From Home 5 Types Data Entry',
 'Data Entry Operator',
 'Data Analyst | Business Analytics | MIS Executive | Fresher - call -9717266846 | 8745833047']

In [15]:
company

['Vivek Manthan Foundation',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'Shri N R Steel Trading Co',
 'Metro Jobs Consultants',
 'SnapHunt Pte Ltd',
 'Esther Jeevitha (Proprietor of Morgan Techno India)',
 'Metro Jobs Consultants',
 'Meksa Enterprises',
 'Hire Zone Solution',
 'Hire Zone Solution',
 'Hire Zone Solution',
 'Hire Zone Solution',
 'Advance Jobs Private Limited',
 'Advance Jobs Private Limited',
 'Minanshika Softech Solution Private Limited',
 'VServ Business Solutions Private Limited',
 'Zarbex Solutions',
 'Aryan Solutions Pte Ltd',
 'Aayam Consultants',
 'Fortunate Services',
 'Fortunate Services',
 'Advance Jobs Private Limited',
 'Meksa Enterprises',
 'Zarbex Solutions',
 'Reynold Infotek',
 'VServ Business Solutions Private Limited',
 'VServ Business Solutions Private Limited',
 'Zarbex Solutions',
 'Biz Industries',
 'Larsen & Toubro Infotech Limited',
 'Structured Learning Assistance Consultants India Private Limited',
 'ABC Consultants Private Limited',
 'Rrai Flight Reservations',
 'Singh RanjayKumar(Proprietor Of Zee India Co)',
 'Immortal Technology And Engineering Consultancy',
 'Wonder Job Services',
 'Hire Zone Solution',
 'VServ Business Solutions Private Limited',
 'Wonder Job Services',
 'Aaryan Technology',
 'Wonder Job Services',
 'Biz Industries',
 'Biz Industries',
 'Biz Industries',
 'Biz Industries',
 'Biz Industries',
 'Wonder Job Services',
 'Infinity HR Solutions',
 'HR Connect One Consultants',
 'Muskaan Parveen (Proprietor Of Muskan Industry)',
 'Muskaan Parveen (Proprietor Of Muskan Industry)',
 'Free Lancer Rishi Kumar',
 'Free Lancer Rishi Kumar',
 'Eccentric Solution And Services',
 'Biz Industries',
 'Hire Zone Solution',
 'Biz Industries',
 'Rudraksha Fire Security Services',
 'PERFECT SOLUTIONS',
 'Star Tech',
 'Biz Industries',
 'Zarbex Solutions',
 'Zarbex Solutions',
 'PERFECT SOLUTIONS',
 'Zarbex Solutions',
 'Hire Zone Solution',
 'STT Solution',
 'Star Tech',
 'Zarbex Solutions',
 'STT Solution',
 'Star Tech',
 'Hire Zone Solution',
 'Shri TirupatiI Balaji Education Foundation',
 'PERFECT SOLUTIONS',
 'Angel And Genie',
 'Zarbex Solutions',
 'Hiren B Patel (Proprietor Of Bajaj India Service)',
 'Structured Learning Assistance Consultants India Private Limited']

In [16]:
location

['Delhi',
 'Delhi, Noida',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Noida',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Noida',
 'Delhi, Noida',
 'Delhi, Noida',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Ghaziabad',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Ghaziabad',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Faridabad',
 'Delhi',
 'Delhi, Aligarh',
 'Delhi, Mumbai, Mumbai City, Navi Mumbai, Thane',
 'Delhi, Pune',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi, Pune',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Noida',
 'Delhi, Noida',
 'Delhi, Gurgaon / Gurugram',
 'Chennai, Delhi',
 'Delhi, Mumbai, Mumbai City, Navi Mumbai, Thane',
 'Bengaluru / Bangalore, Delhi',
 'Bengaluru / Bangalore, Delhi',
 'Delhi, Pune',
 'Delhi, Mumbai',
 'Chennai, Delhi',
 'Delhi, Hyderabad / Secunderabad',
 'Chennai, Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi, Lucknow',
 'Chennai, Delhi',
 'Delhi, Hyderabad / Secunderabad',
 'Delhi, Vellore',
 'Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Hyderabad / Secunderabad',
 'Delhi, Noida',
 'Delhi, Hyderabad / Secunderabad',
 'Bengaluru / Bangalore, Delhi',
 'Delhi',
 'Delhi, Hyderabad / Secunderabad',
 'Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi',
 'Bengaluru / Bangalore, Delhi',
 'Delhi, Noida',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Ahmedabad, Delhi',
 'Delhi, Gurgaon / Gurugram',
 'Delhi, Gurgaon / Gurugram',
 'Delhi',
 'Delhi, Mumbai, Mumbai City, Navi Mumbai, Thane',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi, Hyderabad / Secunderabad',
 'Delhi',
 'Delhi, Mumbai, Mumbai City, Navi Mumbai, Thane',
 'Delhi, Gurgaon / Gurugram',
 'Bengaluru / Bangalore, Delhi',
 'Bengaluru / Bangalore, Delhi',
 'Delhi, Noida',
 'Delhi, Mumbai',
 'Delhi',
 'Delhi',
 'Chennai, Delhi',
 'Chennai, Delhi',
 'Chennai, Delhi',
 'Delhi, Raipur',
 'Bengaluru / Bangalore, Delhi',
 'Chennai, Delhi',
 'Delhi',
 'Delhi, Noida',
 'Delhi',
 'Delhi, Faridabad',
 'Delhi, Vijayawada',
 'Delhi, Noida',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi, Bhilwara',
 'Delhi',
 'Delhi',
 'Delhi, Ghaziabad',
 'Delhi, Gurgaon / Gurugram',
 'Bengaluru / Bangalore, Delhi',
 'Delhi',
 'Delhi, Ghaziabad',
 'Delhi, Noida',
 'Delhi, Noida',
 'Delhi, Mandya',
 'Delhi, Kashipur',
 'Delhi, Hyderabad / Secunderabad',
 'Delhi, Kolkata',
 'Delhi, Dehradun',
 'Delhi',
 'Delhi',
 'Delhi',
 'Delhi, Lucknow']

In [17]:
experience

['0-1 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '3-6 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '1-7 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-3 Years',
 '1-2 Years',
 '2-5 Years',
 'Fresher',
 '0-5 Years',
 '0-5 Years',
 '0-1 Years',
 '0-1 Years',
 '1-3 Years',
 '0-1 Years',
 '0-1 Years',
 '0-5 Years',
 '0-2 Years',
 '0-2 Years',
 '4-8 Years',
 '3-8 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '4-7 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '4-10 Years',
 'Fresher',
 '3-8 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '1-3 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '3-10 Years',
 '0-5 Years',
 '0-5 Years',
 '0-3 Years',
 '0-5 Years',
 'Fresher',
 '5-13 Years',
 '2-10 Years',
 '4-9 Years',
 '0-5 Years',
 '0-2 Years',
 '4-9 Years',
 '0-5 Years',
 '16-22 Years',
 '0-1 Years',
 '0-3 Years',
 '0-5 Years',
 '0-2 Years',
 '0-1 Years',
 '7-13 Years',
 '0-2 Years',
 '0-5 Years',
 '1-4 Years',
 '0-5 Years',
 '0-2 Years',
 '0-5 Years',
 '0-2 Years',
 '0-2 Years',
 '0-2 Years',
 '0-5 Years',
 '0-2 Years',
 '0-5 Years',
 '0-2 Years',
 '4-9 Years',
 '0-5 Years',
 '0-2 Years',
 '5-10 Years',
 '0-1 Years',
 '0-1 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 'Fresher',
 'Fresher',
 '1-8 Years',
 '0-2 Years',
 '0-1 Years',
 '0-2 Years',
 '0-2 Years',
 '0-5 Years',
 '0-1 Years',
 '0-2 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-5 Years',
 '0-1 Years',
 '0-1 Years',
 '0-1 Years',
 '0-5 Years',
 '0-5 Years',
 '0-1 Years',
 '0-1 Years',
 '0-1 Years',
 'Fresher',
 'Fresher',
 '0-5 Years',
 'Fresher',
 '0-5 Years',
 '10-15 Years',
 '0-5 Years',
 '0-1 Years',
 '0-5 Years']

In [18]:
print(len(job_title),len(company),len(location),len(experience))

125 92 125 125

In [19]:
delhi_jobs=pd.DataFrame({})
delhi_jobs['Title']=job_title[:92]
delhi_jobs['Company Name']=company
delhi_jobs['Location']=location[:92]
delhi_jobs['Experience']=experience[:92]
delhi_jobs

,Title,Company Name,Location,Experience
0,Data Scientist,Vivek Manthan Foundation,Delhi,0-1 Years
1,Data Analyst / Fresher / Data Scientist / Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Noida",0-5 Years
2,Data Analyst / Fresher / Data Scientist / Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Gurgaon / Gurugram",0-5 Years
3,Data Analyst / Fresher / Data Scientist / Grad...,Structured Learning Assistance Consultants Ind...,"Delhi, Gurgaon / Gurugram",0-5 Years
4,Data Scientist - Machine Learning,Structured Learning Assistance Consultants Ind...,"Delhi, Gurgaon / Gurugram",3-6 Years
...,...,...,...,...
87,Data Entry Operator,PERFECT SOLUTIONS,"Delhi, Noida",0-2 Years
88,Sales Manager-Data Security Solution/Cloud Sol...,Angel And Genie,"Delhi, Mumbai",5-10 Years
89,data entry operators,Zarbex Solutions,Delhi,0-1 Years
90,Data Entry operators,Hiren B Patel (Proprietor Of Bajaj India Service),Delhi,0-1 Years
91,PART TIME WORK@Home DATA Entry/Home Based WORK...,Structured Learning Assistance Consultants Ind...,"Chennai, Delhi",0-5 Years

In [20]:
#Saving both data in csv files respectively
jobs.to_csv("Software Developer jobs.csv")

In [21]:
delhi_jobs.to_csv("DS Delhi jobs.csv")